name: Verify if the files are properlly formated

on:
  push:
    branches: ['*']

concurrency:
  group: "formating"
  cancel-in-progress: true

jobs:
  checking-format:
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0

      - name: Check the formating
        run: pnpm prettier
